python -u run.py \
    --task_name pretrain \
    --downstream_task classification \
    --root_path datasets/eeg_no_big/ \
    --model_id EEG \
    --model TimeDART \
    --data EEG \
    --e_layers 2 \
    --d_layers 1 \
    --input_len 3000 \
    --enc_in 2 \
    --dec_in 2 \
    --c_out 2 \
    --num_classes 8 \
    --n_heads 16 \
    --d_model 128 \
    --d_ff 256 \
    --patch_len 75 \
    --stride 75 \
    --head_dropout 0.2 \
    --dropout 0.2 \
    --time_steps 1000 \
    --scheduler cosine \
    --lr_decay 0.95 \
    --learning_rate 0.001 \
    --batch_size 128 \
    --train_epochs 50 \
    --gpu 0
